Update stp.md
GSTT-CSC/csc-test-site pull request #121
Opened 2022-07-12 19:28 UTC by hshuaib90

Fixes #120

2022-07-12 20:54 UTC, heyhaleema requested changes
Content looks 👌 ! I've left a few comments for some minor formatting edits before this gets merged.

2022-07-12 20:54 UTC, heyhaleema commented on _pages/stp.md
> +2
It seems like this is a line number?

2022-07-12 20:54 UTC, heyhaleema commented on _pages/stp.md
> +·       changes to [rotations](https://nshcs.hee.nhs.uk/programmes/stp/trainers/guidance-for-working-with-the-2022-stp-curricula/rotation-modules/) which now provide trainees with an understanding of
This bullet point format doesn't seem to render well on the page/match the previous bullet point formatting:

``` suggestion
-  changes to [rotations](https://nshcs.hee.nhs.uk/programmes/stp/trainers/guidance-for-working-with-the-2022-stp-curricula/rotation-modules/) which now provide trainees with an understanding of their specialty and the wider healthcare environment around them,
```

2022-07-12 20:54 UTC, heyhaleema commented on _pages/stp.md
> +·       the [work-based curriculum](https://nshcs.hee.nhs.uk/programmes/stp/trainers/guidance-for-working-with-the-2022-stp-curricula/the-work-based-curriculum/) including the updated competencies an
```suggestion
- the [work-based curriculum](https://nshcs.hee.nhs.uk/programmes/stp/trainers/guidance-for-working-with-the-2022-stp-curricula/the-work-based-curriculum/) including the updated competencies and considerations, work-based assessments and clinical experiences,
```

2022-07-12 20:54 UTC, heyhaleema commented on _pages/stp.md
> +·       changes to the core modules  including the new [Professional Foundations](https://curriculumlibrary.nshcs.org.uk/stp/module/S-C1/) and [Independent Professional Development](https://curriculu
```suggestion
- changes to the core modules including the new [Professional Foundations](https://curriculumlibrary.nshcs.org.uk/stp/module/S-C1/) and [Independent Professional Development](https://curriculumlibrary.nshcs.org.uk/stp/module/S-C4/) modules. We’d suggest starting to look at both of these modules with trainees as they start, there’s lots to consider as they begin to develop their professional skills and knowledge. 
```

2022-07-12 20:54 UTC, heyhaleema commented on _pages/stp.md
> +10
Weirdly, there were [zero width-spaces](https://en.wikipedia.org/wiki/Zero-width_space) here and in other lines - maybe related to the formatting/line numbers? I don't think it actually affects how the page looks, though.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/67117138/178591740-6da60aa8-cc78-4362-b04b-30077929f7fe.png">

2022-07-23 21:55 UTC, hshuaib90 commented
Sorry @heyhaleema idk what happened with the formatting and numbers, it was horrendous. I think a copy-paste job gone wrong! I should've been more diligent, sorry. Hopefully, now it's fine.

2022-07-26 20:53 UTC, heyhaleema approved these changes
No worries! New content is 🔥

2022-07-26 20:54 UTC, merged