Profile
GSTT-CSC/csc-test-site pull request #135
Opened 2022-08-31 10:00 UTC by aysha1207

Can you check if my profile is ok to upload to the website

2022-09-02 13:45 UTC, tomaroberts commented on _data/team.yml
> +      name: Aysha Luis
Hi @aysha1207 

Careful with the formatting – line 118 needs a hyphen before `name` and the indentation of the subsequent lines needs to be consistent with the rest of the file because of the way `.yml` files work.

2022-09-02 13:47 UTC, tomaroberts commented on _data/team.yml
> +        -
Similarly, this stray hyphen is breaking the code when I try to build it.

I can fix this, but it would be a good exercise for you to do it!

2022-09-02 13:49 UTC, tomaroberts requested changes
@aysha1207 – there are a few errors in the code you submitted. Also, you need to add a photo and a biography page like this one: https://gstt-csc.github.io/team_member/alex.html

@Lucrezia-Cester – would you be able to help Aysha get her profile on the website?

2022-09-02 14:31 UTC, Lucrezia-Cester commented
@tomaroberts Yup, will get a look at this next week

2022-10-03 17:02 UTC, dangerdika commented
@tomaroberts @Lucrezia-Cester @aysha1207 a different branch already solved this problem of adding Aysha to the teams list, it should be deleted. @aysha1207 please make your profile page and pull that instead (& let me or Lu know if you need a hand with doing so!)

2022-11-08 21:14 UTC, hshuaib90 commented
@aysha1207 im closing this PR as it's no longer needed

2022-11-08 21:14 UTC, closed without merging