#37 add trainee onboarding section
GSTT-CSC/csc-test-site pull request #205
Opened 2023-04-13 15:54 UTC by AnilMistry

Resolves #37

2023-04-13 17:00 UTC, hshuaib90 requested changes
Thanks Anil, this is great. Just a couple of typos. Also what's with the image? Can we get a more specific one?

2023-04-13 17:00 UTC, hshuaib90 commented on _handbook/onboarding.md
> +   - your password
Is this typo? Not sure why new line

2023-04-13 17:00 UTC, hshuaib90 commented on _pages/getinvolved.md
> +- Healthcare Science (NSHCS) Scientist Training Programme (STP). The NSHCS STP allows trainees to allocate part of the
Again, probably a typo, not a new line

2023-04-13 17:00 UTC, hshuaib90 commented on _pages/stp.md
> +- Undertake addition [Educator training](https://portal.e-lfh.org.uk/myElearning/Index?HierarchyId=0_54104_54116&programmeId=54104)
typo: additional

2023-04-18 08:15 UTC, AnilMistry commented
I've also removed the photo, until we have a better policy on photo themes!

2023-04-18 08:23 UTC, hshuaib90 approved these changes

2023-04-18 08:24 UTC, merged