Adds guide on how to contribute to website development
GSTT-CSC/csc-test-site pull request #206
Opened 2023-04-14 17:56 UTC by heyhaleema

This PR resolves #175.

**Notes for reviewer feedback** 

- The [original guide](https://github.com/GSTT-CSC/gstt-csc-old/blob/6415913c97f175e457e1ce999c301f37916c8ad3/howto.md) advised contributors to raise PRs to merge into the `main` branch i.e., now `gh-pages`. I've changed this to `develop` since I noticed there is one in the repo, plus it seems to be the norm for our contributing guidelines in other repos.
- I've removed the explicit instructions on, for example, cloning the repository, local installation, etc. and linked to the official or original source of documentation to avoid (1) duplication of work and (2) content consistency.

2023-04-15 12:29 UTC, hshuaib90 commented
Thanks @heyhaleema ! This looks great except I don't think we need to have changes merged to develop for the CSC website. Where that is sometimes necessary with other projects where the risk of breaking changes is high, for the website we can merge direct to main if approved.

2023-04-15 12:31 UTC, hshuaib90 requested changes
As mentioned in comment, we don't need to follow Git-Flow for the website, we can branch from main and merge back into main. 

Also is there a reason why you didn't just copy paste the origina instructions? There are some key things missing like building the website locally and advice for M1 Macs.

2023-04-17 09:21 UTC, heyhaleema commented
@hshuaib90 I've now updated the target branch guidance to advise merging into `gh-pages`, and I've added the Apple Silicon (ARM) e.g., M1 Mac user local setup guidance to the README. I opted not to copy the full guidance into this guide because I felt that this would be duplicating the [Install section in the README](https://github.com/GSTT-CSC/gstt-csc.github.io#install) and that users would find their way to this section in the first couple of steps of the guide.

2023-04-17 09:24 UTC, hshuaib90 approved these changes

2023-04-17 09:24 UTC, merged