Add Sophie's short bio
GSTT-CSC/csc-test-site pull request #221
Opened 2023-07-03 10:50 UTC by sophie22

resolves #219

2023-07-03 12:32 UTC, AnilMistry requested changes

2023-07-03 12:32 UTC, AnilMistry commented on _team_member/sophie.md
> +Sophie is currently working on improvements to Hazen, a quality assurance framework for MR imaging, and its web app version. She is also being trained to build, train, evaluate and deploy machine lea
I would change this to: 

Sophie is currently working on improvements to Hazen, a quality assurance framework for MR imaging, and its web app version. She is also involved in building, training, evaluating and deploying machine learning models, leading on the MRI wrist fracture detection model.

2023-07-03 13:45 UTC, sophie22 commented
updated role description as requested

2023-07-04 08:30 UTC, AnilMistry commented
Apoliges, i have missed something here, could you also fill in -data/team.yml file, filling out a new section for yourself?

2023-07-04 10:30 UTC, AnilMistry requested changes
final issue to resolve, then we're good. After committing the change can you re-request me as a review on the PR?

2023-07-04 10:30 UTC, AnilMistry commented on _data/team.yml
> +        image: assets/img/team/SophieR.png
This should be SophieR.jpeg

2023-07-04 10:35 UTC, AnilMistry approved these changes
brilliant, works locally for me.

2023-07-04 10:35 UTC, merged