Landscape layout 2
GSTT-CSC/csc-test-site pull request #27
Opened 2022-02-21 14:54 UTC by Lucrezia-Cester

2022-02-21 14:54 UTC, Lucrezia-Cester commented
Hi @tomaroberts, this is now ready for review. I have created a new PR since I changed many things compared to the other landscape PR I had opened.

2022-02-23 11:01 UTC, tomaroberts requested changes
Hi Lu, thanks for this. I have a meeting so slightly in a rush, but...

- Broad issue: we need to decide as a group exactly what we want in this page. But the platforms you've listed are a logical starting point. I wonder if we want to sub-divide into Internal and External platforms.
- The images need to be hyperlinks to pages specifically about the platforms. I think we should keep people on the site rather than just linking to the external pages, so we could have little summaries of the platforms and how we work with them/use them.
- If I shrink my browser window, the images overlap, which they shouldn't. This is a bootstrap issue. I have the same problem on the About Us page. It's unlikely people will see this issue, so not super urgent, but something we should fix.

If I think of anything else, I'll add some more comments. Thanks for this - already raised various questions in my mind!

2022-02-23 11:01 UTC, tomaroberts commented on _includes/landscape.html
> +		  <img style="width: 300px; height:200px; padding = 1px; border: 8px solid transparent; background: linear-gradient(90deg, #e1f0d0 100%, #ce00 100%)" src="{{ platform.image }}" alt="">
The aspect ratio of the images is non-square, which looks bad. This is because you have both width and height tags hard-coded. If you remove the height tag, then the code should retain the aspect ratio of the underlying images. You will need to standardise the aspect ratio of the images you use, otherwise the images will be different sizes on the page. The easiest way to do this might be to just ensure all the images are say 400px x 400px, or whatever looks best.

I'm also not keen on the green border around the images, but I think the style of the site has yet to emerge, so for now I would probably just use a dull thin black line or something until we figure out what styling we want to use.

2022-02-23 11:01 UTC, tomaroberts commented on _includes/landscape.html
> +<h5 class="text-muted">Click on the platforms to find out more about them.</h5>
You could replace this line with the `text:` entry in your .yml file if you want.

2022-02-23 11:01 UTC, tomaroberts commented on thelandscape.md
> +layout: landscape_l
Can you rename this "landscape" and the update the accompanying places it's used in the code, just to maintain code convention.

2022-02-23 11:01 UTC, tomaroberts commented on _data/landscape.yml
> +    text: "Click on the platform to find out more about each paltform."
Typo: platform

2022-03-14 15:39 UTC, tomaroberts commented
Hi Lu – there is a problem with your latest set of commits. When I run the site based on this branch, it looks like this:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/15610752/158205810-13e82b5c-e015-402a-b78d-332caffce08f.png">

I think you have deleted the images from the repo?

Some other requests. Can you:
- [ ] update the navbar code so that the PLATFORMS button redirects to `landscape.html`
- [ ] based on the latest Wednesday workshop, add the platform names to the subnav bar. So, it should be like:

| ABOUT US | PEOPLE | PLATFORMS | POLICY | OUR WORK | BLOG |
| - | - | - | - | - | - |
| LANDSCAPE | AIDE | FLIP | CogStack | XNAT | MLOps |

- [ ] above the images, add some introductory text giving a general sense of what the page is about and we are making these platforms.

2022-05-04 12:35 UTC, Lucrezia-Cester commented
Hi @tomaroberts, I have addressed your comments. It is now ready for review.

2022-05-13 10:02 UTC, merged