Add Sam's Blog
GSTT-CSC/csc-test-site pull request #516
Opened 2024-12-13 13:18 UTC by EStyli

Edited blog to ~912 words, originally 1352 words

2024-12-18 12:17 UTC, AnilMistry requested changes
Good work, just a few things to update then happy to approve.

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +title: From Biochemistry to Binary: My Journey with the CSC Team
if using a colon, please put the whole string in quotes, otherwise formatting of the yaml frontmatter messes up

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +image: /assets/img/blog/Sam_TeamCSC.png
should be .jpg

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +title: From Biochemistry to Binary: My Journey with the CSC Team
also can you change this to "From BioChem to Binary: My Journey with CSC" to make it shorter so the blogpost card fits the formatting

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +Overall, I had a fantastic time with the CSC team - on top of it being a genuinely valuable professional learning experience, the team made me feel welcome and involved (in spite of some of their opi
guy's and st thomas', dont forget the final apostrophe

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +I attended the CSC "AI Fairness Club" (official name TBC) inaugural meeting and got involved with planning a literature review. This is the brainchild of CSC Deputy Head [Dika Vilic] (https://gstt-cs
remove spaces between [] and () for the links to work

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +I quickly learned that the CSC teams' work is much more complicated than I had originally considered. AI is being well implemented within medical physics and radiology, representing much of the CSC's
remove spaces between [] and () for the links to work

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +I quickly learned that the CSC teams' work is much more complicated than I had originally considered. AI is being well implemented within medical physics and radiology, representing much of the CSC's
RAVE is the Referral Automated vetting engine - please add full title as well as acronym

2024-12-18 12:17 UTC, AnilMistry commented on blogs/articles/_posts/2024-05-25-STP_blog_Sam.md
> +I attended the CSC "AI Fairness Club" (official name TBC) inaugural meeting and got involved with planning a literature review. This is the brainchild of CSC Deputy Head [Dika Vilic] (https://gstt-cs
is there an official name for the ai fairness + link on website now?

2024-12-19 12:49 UTC, EStyli reviewed
Review Sam Blog Edits
added quoation marks where needed, removed spaces for links to work, shotened title, added Sam's image and cropped main image and made other minor edits.

2024-12-27 17:58 UTC, dangerdika approved these changes
Loads well, cant find any typos, all problems @AnilMistry commented on have been resolved. Thank you @EStyli, merging this now!

2024-12-27 18:00 UTC, merged